version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=your_db_username
      - DATABASE_PASSWORD=your_db_password
      - DATABASE_NAME=hotel_db
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: 
      POSTGRES_DB: hotel_db
    ports:
      - '5432:5432'
